app/urls.py
from django.urls import path

from .views import *

app_name = "main_app"

urlpatterns = [
    path('', HomePageView.as_view(), name="homepage"),
    path('blog/<str:slug>/', DetailViews.as_view(), name='detailview'),
    path('category/<str:slug>/', CategoriesView.as_view(), name='categories'),
    path('region/<str:slug>/', RegionsView.as_view(), name='regions'),
]

blogsite/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns


urlpatterns = [
    path('admin/', admin.site.urls),
    path('i18n', include('django.conf.urls.i18n')),
]

urlpatterns += i18n_patterns(
    path('', include('app.urls')),
)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/models.py
from django.db import models
from parler.models import TranslatableModel, TranslatedFields
from django.utils.translation import gettext_lazy as _


class Regions(TranslatableModel):
    translation = TranslatedFields(
        name=models.CharField(max_length=255, blank=True, null=True, verbose_name=_('Name'))
    )
    slug = models.SlugField(max_length=255, unique=True, blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'Regions'

    def __str__(self):
        return self.safe_translation_getter('name') or ''

    def get_absolute_url(self):
        return f'regions/{self.slug}'


class Category(models.Model):
    name = models.CharField(max_length=255, blank=True, null=True)
    slug = models.SlugField(max_length=255, unique=True, blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = "Categories"

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return f'categories/{self.slug}'


class Blog(TranslatableModel):
    translations = TranslatedFields(
        title=models.CharField(max_length=255, verbose_name=_('Title')),
        description=models.TextField(verbose_name=_('Description')))
    slug = models.SlugField(max_length=255, unique=True)
    created_at = models.DateTimeField(auto_now_add=True,)
    image = models.ImageField(upload_to='blogimages')
    region = models.ForeignKey(Regions, on_delete=models.CASCADE,)
    category = models.ForeignKey(Category, on_delete=models.CASCADE,)
    hashtag = models.ForeignKey('Hashtags', on_delete=models.CASCADE)

    class Meta:
        verbose_name_plural = 'Blog'

    def __str__(self):
        return self.safe_translation_getter('title') or ''

    def get_absolute_url(self):
        return f'blog/{self.slug}'


class Hashtags(models.Model):
    name = models.CharField(max_length=255, blank=True, null=True)
    slug = models.SlugField(max_length=255, blank=True, null=True)

    class Meta:
        verbose_name_plural = 'Hashtags'

    def __str__(self):
        return self.name


class PicturesFromTheBlog(models.Model):
    owner = models.ForeignKey(Blog, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='shotsinblogs')

    class Meta:
        verbose_name_plural = 'Pictures from the blog'

    def __str__(self):
        return self.owner.safe_translation_getter('title') or ''

app/forms.py
from parler.forms import TranslatableModelForm, TranslatedField

from .models import Blog


class BlogForm(TranslatableModelForm):
    title = TranslatedField()
    description = TranslatedField()

    class Meta:
        model = Blog
        fields = ('title', 'slug', 'description', 'image', 'region', 'category','hashtag')

app/views.py
from django.views.generic import ListView, DetailView

from .models import *


class HomePageView(ListView):
    template_name = 'index.html'
    queryset = Blog.objects.all()

    # custom_context_processor.py bu funksiyani bajaradi

    # def get_context_data(self, *args, **kwargs):
    #     context = super().get_context_data()
    #     context['category'] = Category.objects.all()
    #     context['regions'] = Regions.objects.all()
    #     return context


class DetailViews(DetailView):
    model = Blog
    template_name = 'detail.html'

    def get_context_data(self, **kwargs):
        context = super(DetailViews, self).get_context_data(**kwargs)
        return context


class CategoriesView(ListView):
    template_name = 'hashtag.html'
    model = Blog

    def get_queryset(self):
        queryset = self.model.objects.filter(category__slug=self.kwargs.get('slug'))
        return queryset

class RegionsView(ListView):
    template_name = 'regions.html'
    model = Blog

    def get_queryset(self):
        queryset = self.model.objects.filter(region__slug=self.kwargs.get('slug'))
        return queryset

templates/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h1>{{ object.title }}</h1> <br><br>
    <h1>{{ object.created_at }}</h1>
    <img src="{{ object.image.url }}" alt="">
    <p>{{ object.description | safe }}</p>
    <a href="">#{{ object.hashtag }}</a>
</body>
</html>

templates/hashtag.html
<!DOCTYPE html>
{% load static i18n %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

    {% for datas in object_list %}
        <a href="{% url 'main_app:detailview' slug=datas.slug %}">{{ datas.title | safe}}</a><br>
        {% if datas.image %}<br>

            <img src="{{ datas.image.url }}" alt=""><br>
        {% endif %}
        {{ datas.description | safe | truncatechars:100 }}<br>
    {% endfor %}

</body>
</html>

templates/index.html
<!DOCTYPE html>
{% load static i18n %}
{% load app_tags %}
{% get_current_language as LANGUGES_CODE %}
{% get_available_languages as languages %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<ul class="list-group" id="list-group">
    {% for language , title in languages %}
        <li id="en" onclick="changeSelect('En')" {% if language == LANGUGES_CODE %}{% endif %}>
            {% get_url_tag request=request lang=language as url %}<a href="{{ url }}">{{ language }}</a></li>
    {% endfor %}
</ul>

<body>
    <div style="margin: 0px ; padding: 0px">
        {% for categories in all_category %}
        <a href="{% url 'main_app:categories' slug=categories.slug %}"> {{ categories.name }}</a>
        {% endfor %}
    </div>


    <div style="margin: 0px ; padding: 0px">
        {% for names in all_regions %}
        <a href="{% url 'main_app:regions' slug=names.slug %}"> {{ names.name }}</a>
        {% endfor %}
    </div>

    {% for datas in object_list %}
        <a href="{% url 'main_app:detailview' slug=datas.slug %}">{{ datas.title | safe}}</a><br>
    {% if datas.image %}<br>

    <img src="{{ datas.image.url }}" alt=""><br>
    {% endif %}
     {{ datas.description | safe | truncatewords:10 }}<br>
    {% endfor %}

    <h1>{% trans  'Tarjima boladigan text' %}</h1>
     <h1>{% trans  'Tarjima boladigan text' %}</h1>
      <h1>{% trans  'Tarjima boladigan text' %}</h1>
</body>
</html>

templates/regions.html
<!DOCTYPE html>
{% load static i18n %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

    {% for datas in object_list %}
        <a href="{% url 'main_app:detailview' slug=datas.slug %}">{{ datas.title | safe}}</a><br>
        {% if datas.image %}<br>

            <img src="{{ datas.image.url }}" alt=""><br>
        {% endif %}
        {{ datas.description | safe | truncatewords:10 }}<br>
    {% endfor %}

</body>
</html>